### ISSUE TITLE
opsional

### ISSUE THREAD

**Issue by pacenadhif777** [itsFrankV22/ESSENTIALS-GetInfoUtil#1]
my advice is to use characters that support the mobile version as well as for your stats sign use the === sign and under it also use === so that it is not visible * and my advice is that messages when other players enter do not use [+] and remove the [ replace with:
 [i:megaphone] player joined

**Comment by itsFrankV22** [comment]
Thanks for the feedback, I'm currently working on improving it so that it can be configured in a `Config.json` and everything is easier and simpler.

**Comment by pacenadhif777** [comment]
> Thanks for the feedback, I'm currently working on improving it so that it can be configured in a `Config.json` and everything is easier and simpler.

and also don't show the message that i joined only players see it meaning I don't need to see my own name joined [+] i was joined (just dont show it)

**Comment by itsFrankV22** [comment]
@pacenadhif777 Plugin updated, check the latest version!!! Now you can configure the join message to your liking!
